channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.16=habfa6aa_3_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.1.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bitsandbytes==0.45.5
      - boto3==1.39.3
      - botocore==1.39.3
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - contourpy==1.3.2
      - cryoet-data-portal==4.4.1
      - cycler==0.12.1
      - deepmerge==2.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - exceptiongroup==1.3.0
      - fasteners==0.19
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gql==3.5.3
      - graphql-core==3.2.6
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonargparse==4.39.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - monai==1.4.0
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - multidict==6.4.3
      - networkx==3.4.2
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.3.2
      - pillow==11.2.1
      - platformdirs==4.3.7
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - s3transfer==0.13.0
      - scikit-image==0.25.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - strcase==1.0.0
      - sympy==1.14.0
      - tensorboardx==2.6.2.2
      - tifffile==2025.3.30
      - torch==2.7.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - triton==3.3.0
      - typeshed-client==2.7.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.10
      - yarl==1.20.0
      - zarr==2.18.3