channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.10.16=he725a3c_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argcomplete==3.6.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.3
      - boto3==1.37.15
      - botocore==1.37.15
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - dacite==1.7.0
      - deprecated==1.2.18
      - dill==0.3.9
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - fiftyone==1.3.2
      - fiftyone-brain==0.19.0
      - fiftyone-db==1.1.7
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glob2==0.7
      - graphql-core==3.2.6
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - humanize==4.12.1
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - idna==3.10
      - imageio==2.37.0
      - inflate64==1.0.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - monai==1.4.0
      - mongoengine==0.29.1
      - motor==3.6.1
      - mpmath==1.3.0
      - multivolumefile==0.2.3
      - narwhals==1.31.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pprintpp==0.4.0
      - priority==2.0.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - py7zr==0.22.0
      - pybcj==1.0.3
      - pycocotools==2.0.8
      - pycryptodomex==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydash==8.0.5
      - pymongo==4.9.2
      - pyparsing==3.2.1
      - pyppmd==1.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzstd==0.16.2
      - rarfile==4.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rtree==1.4.0
      - s3transfer==0.11.4
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sse-starlette==0.10.3
      - sseclient-py==1.8.0
      - starlette==0.46.1
      - strawberry-graphql==0.262.5
      - sympy==1.13.1
      - tabulate==0.9.0
      - taskgroup==0.2.2
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - tomli==2.2.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - tzlocal==5.3.1
      - universal-analytics-python3==1.1.1
      - urllib3==2.3.0
      - voxel51-eta==0.14.0
      - wandb==0.19.8
      - wcwidth==0.2.13
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xmltodict==0.14.2